# Generated by Django 2.2.2 on 2019-06-07 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 0, 19, 6, 736102), verbose_name='Date Published'),
        ),
    ]
